# Generated by Django 3.0.8 on 2020-08-16 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200816_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='time_posted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
