# Generated by Django 3.0.8 on 2020-08-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_skillset_time_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='yn',
            field=models.BooleanField(help_text='Yes or No'),
        ),
    ]
