# Generated by Django 3.0.8 on 2020-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200816_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='yn',
            field=models.BooleanField(verbose_name='Yes or No'),
        ),
    ]
